// ============================================================
// Seb's Complete Wine Guide — the data
// Every wine has: category, colours for its illustration,
// tasting stats (0-5), and a pile of facts.
// ============================================================

const CATEGORIES = {
  red:       { label: "Red Wines",       blurb: "Made from dark-skinned grapes fermented with their skins, which give the wine its colour, tannin and structure." },
  white:     { label: "White Wines",     blurb: "Usually made from green grapes (sometimes dark grapes with the skins removed), fermented cool to keep them fresh and aromatic." },
  rose:      { label: "Rosé Wines",      blurb: "Made from red grapes whose juice spends only a few hours on the skins — just long enough to blush pink." },
  sparkling: { label: "Sparkling Wines", blurb: "Wines with trapped carbon dioxide bubbles, usually from a second fermentation in bottle or tank." },
  dessert:   { label: "Dessert Wines",   blurb: "Lusciously sweet wines made from super-ripe, dried, frozen or nobly-rotted grapes." },
  fortified: { label: "Fortified Wines", blurb: "Wines strengthened with grape spirit, historically so they could survive long sea voyages." },
  orange:    { label: "Orange & Skin-Contact", blurb: "White grapes fermented like reds — with their skins — giving amber colour, tannin and wild aromas. One of the oldest styles of wine on Earth." }
};

const WINES = [
  // ================= RED WINES =================
  {
    id: "cabernet-sauvignon",
    name: "Cabernet Sauvignon",
    pronounce: "kab-er-nay soh-vin-yon",
    category: "red",
    tagline: "The king of red grapes",
    hue: ["#6b1024", "#2e0510"],
    origin: "Bordeaux, France (17th century)",
    regions: ["Bordeaux (Left Bank)", "Napa Valley, USA", "Coonawarra & Margaret River, Australia", "Maipo Valley, Chile", "Tuscany, Italy"],
    abv: "13.5–15%",
    sweetness: 0, body: 5, tannin: 5, acidity: 3,
    servingTemp: "16–18 °C (60–65 °F)",
    glassware: "Large Bordeaux glass",
    flavors: ["Blackcurrant (cassis)", "Black cherry", "Cedar", "Green bell pepper", "Tobacco", "Vanilla & baking spice from oak"],
    pairings: ["Ribeye steak", "Lamb chops", "Aged cheddar", "Portobello mushrooms", "Dark chocolate"],
    description: "The most planted wine grape on the planet and the backbone of the world's most collectible reds. Cabernet Sauvignon is thick-skinned and late-ripening, producing deeply coloured, full-bodied wines with firm tannins that let the best examples age gracefully for decades.",
    facts: [
      "DNA testing in 1996 revealed Cabernet Sauvignon is a natural cross of Cabernet Franc and Sauvignon Blanc — a red grape with a white parent.",
      "It is the most widely planted wine grape in the world, covering around 340,000 hectares.",
      "The 1976 'Judgment of Paris' blind tasting saw a Napa Cabernet (Stag's Leap 1973) beat top Bordeaux, shocking the wine world.",
      "Its thick skins are rich in tannin, which acts as a natural preservative — top Cabernets can improve in bottle for 30+ years.",
      "The classic 'pencil shavings' and cedar notes come from ageing in oak barrels, often new French oak."
    ]
  },
  {
    id: "merlot",
    name: "Merlot",
    pronounce: "mer-loh",
    category: "red",
    tagline: "The velvet diplomat",
    hue: ["#7a1c30", "#3a0a16"],
    origin: "Bordeaux, France (first noted 1784)",
    regions: ["Bordeaux (Right Bank: Pomerol, Saint-Émilion)", "Washington State, USA", "California", "Tuscany, Italy", "Chile"],
    abv: "13–14.5%",
    sweetness: 0, body: 4, tannin: 3, acidity: 3,
    servingTemp: "15–18 °C (60–64 °F)",
    glassware: "Bordeaux glass",
    flavors: ["Plum", "Black cherry", "Chocolate", "Bay leaf", "Vanilla", "Soft mocha"],
    pairings: ["Roast chicken", "Pork tenderloin", "Mushroom risotto", "Gouda", "Beef bourguignon"],
    description: "Merlot is Cabernet's softer, plusher sibling — rounder tannins, juicier fruit and an approachability that makes it one of the world's favourite reds. In Pomerol it produces some of the most expensive wines on Earth, including the legendary Pétrus.",
    facts: [
      "The name comes from 'merle', French for blackbird — either for the grape's blue-black colour or the birds' fondness for eating it.",
      "Merlot is the most planted grape in Bordeaux, not Cabernet Sauvignon — it covers about 60% of the region's red vineyards.",
      "Château Pétrus, made almost entirely from Merlot, sells for thousands of pounds a bottle.",
      "The 2004 film 'Sideways' famously trashed Merlot and measurably dented US sales — the so-called 'Sideways effect' — while boosting Pinot Noir.",
      "Merlot ripens about two weeks earlier than Cabernet Sauvignon, which is why Bordeaux blends the two as insurance against bad weather."
    ]
  },
  {
    id: "pinot-noir",
    name: "Pinot Noir",
    pronounce: "pee-noh nwahr",
    category: "red",
    tagline: "The heartbreak grape",
    hue: ["#96283f", "#571225"],
    origin: "Burgundy, France (documented since 1st century AD)",
    regions: ["Burgundy (Côte d'Or)", "Oregon, USA", "Central Otago & Martinborough, NZ", "Sonoma Coast, USA", "Germany (as Spätburgunder)"],
    abv: "12.5–14%",
    sweetness: 0, body: 2, tannin: 2, acidity: 4,
    servingTemp: "13–16 °C (55–60 °F)",
    glassware: "Wide Burgundy balloon glass",
    flavors: ["Red cherry", "Raspberry", "Rose petal", "Mushroom", "Forest floor", "Warm spice"],
    pairings: ["Duck breast", "Salmon", "Mushroom dishes", "Coq au vin", "Brie & soft cheeses"],
    description: "Thin-skinned, fickle and maddening to grow, Pinot Noir is nicknamed 'the heartbreak grape' — yet when it works, it produces the most ethereal, perfumed and expensive red wines in the world. It is the ultimate expression of terroir: the same grape tastes wildly different from village to village in Burgundy.",
    facts: [
      "Pinot Noir is one of the oldest cultivated grapes — the Romans found it growing in Burgundy nearly 2,000 years ago.",
      "A single bottle of Domaine de la Romanée-Conti 1945 sold for $558,000 in 2018 — a world record for wine at auction.",
      "The name means 'black pine', because its small tight bunches resemble a pine cone.",
      "Pinot Noir is genetically unstable and has mutated into Pinot Gris, Pinot Blanc and Pinot Meunier — all the same DNA fingerprint.",
      "It is one of the three permitted grapes of Champagne, where it is pressed gently so the juice stays white."
    ]
  },
  {
    id: "syrah",
    name: "Syrah / Shiraz",
    pronounce: "sih-rah / shih-raz",
    category: "red",
    tagline: "Pepper, power and smoke",
    hue: ["#511027", "#1f050e"],
    origin: "Rhône Valley, France",
    regions: ["Northern Rhône (Hermitage, Côte-Rôtie)", "Barossa Valley, Australia", "Washington State", "South Africa", "Chile"],
    abv: "13.5–15.5%",
    sweetness: 0, body: 5, tannin: 4, acidity: 3,
    servingTemp: "16–18 °C (60–65 °F)",
    glassware: "Large red wine glass",
    flavors: ["Blackberry", "Black pepper", "Smoked meat", "Violet", "Liquorice", "Olive tapenade"],
    pairings: ["Barbecue & smoked brisket", "Venison", "Pepper-crusted steak", "Hard sheep's cheeses", "Sausages"],
    description: "One grape, two personalities: in France's Rhône it makes savoury, peppery, floral 'Syrah'; in Australia it becomes 'Shiraz' — rich, ripe and chocolatey. Either way it delivers some of the darkest, most powerful red wines made anywhere.",
    facts: [
      "DNA profiling proved Syrah is a cross of two obscure French grapes, Dureza and Mondeuse Blanche — killing the romantic legend that it came from Shiraz in Persia.",
      "The distinctive black-pepper aroma comes from the compound rotundone — the same molecule that makes peppercorns peppery.",
      "Australia's oldest Shiraz vines, planted in the 1840s, are among the oldest producing grapevines in the world — Europe's originals were killed by the phylloxera louse.",
      "Penfolds Grange, Australia's most famous wine, is a Shiraz that was nearly discontinued in the 1950s after executives called it 'a very good dry port that no one will buy'.",
      "In Côte-Rôtie, growers traditionally co-ferment Syrah with a splash of white Viognier to fix its colour and lift the perfume."
    ]
  },
  {
    id: "malbec",
    name: "Malbec",
    pronounce: "mal-bek",
    category: "red",
    tagline: "Argentina's adopted champion",
    hue: ["#4e0e33", "#20051a"],
    origin: "Cahors, South-West France",
    regions: ["Mendoza, Argentina", "Cahors, France", "Salta, Argentina (world's highest vineyards)", "Chile"],
    abv: "13.5–15%",
    sweetness: 0, body: 4, tannin: 4, acidity: 3,
    servingTemp: "15–18 °C (59–64 °F)",
    glassware: "Large red wine glass",
    flavors: ["Blackberry", "Plum", "Violet", "Cocoa", "Sweet tobacco", "Vanilla"],
    pairings: ["Grilled steak (asado)", "Empanadas", "Blue cheese", "Chorizo", "Lamb burgers"],
    description: "Once a blending grape in Bordeaux and the 'black wine' of Cahors, Malbec found its true home 11,000 km away in the high-altitude deserts of Mendoza, Argentina, where intense sunshine turns it inky, velvety and irresistibly plummy.",
    facts: [
      "Malbec arrived in Argentina in 1853 when a French agronomist, Michel Pouget, was hired to bring vine cuttings — a date now celebrated as World Malbec Day (17 April).",
      "Medieval Cahors Malbec was called 'the black wine' and was so prized that English kings served it at royal weddings.",
      "Some Malbec vineyards in Salta, Argentina sit above 3,000 m altitude — the highest commercial vineyards on the planet.",
      "The intense UV light at altitude thickens the grapes' skins, giving Argentine Malbec its trademark dark colour and floral aroma.",
      "A devastating frost in Bordeaux in 1956 wiped out most of France's Malbec, which is why it's now rare there but king in Argentina."
    ]
  },
  {
    id: "zinfandel",
    name: "Zinfandel",
    pronounce: "zin-fan-del",
    category: "red",
    tagline: "California's heritage brambler",
    hue: ["#79203a", "#38091a"],
    origin: "Croatia (as Crljenak Kaštelanski / Tribidrag)",
    regions: ["Lodi & Sonoma, California", "Puglia, Italy (as Primitivo)", "Croatia (Dalmatian coast)"],
    abv: "14–16%",
    sweetness: 0, body: 4, tannin: 3, acidity: 3,
    servingTemp: "15–18 °C (59–64 °F)",
    glassware: "Standard red wine glass",
    flavors: ["Blackberry jam", "Raspberry", "Black pepper", "Cinnamon", "Smoky bourbon", "Dried herbs"],
    pairings: ["Barbecue ribs", "Pizza", "Burgers", "Chilli con carne", "Aged gouda"],
    description: "California's own heritage grape — big, jammy, spicy and often gloriously high in alcohol. Century-old gnarled Zinfandel vines still produce tiny crops of intensely flavoured fruit in Lodi and Sonoma.",
    facts: [
      "A decades-long detective hunt ('Zinquest') traced Zinfandel's DNA to an obscure Croatian grape, Crljenak Kaštelanski, in 2001 — it's also identical to Italy's Primitivo.",
      "Some Californian Zinfandel vines are over 130 years old and still producing wine.",
      "Zinfandel bunches ripen unevenly — one cluster can hold both green berries and raisins, which is why the wines taste both fresh and jammy at once.",
      "Sweet pink 'White Zinfandel' was invented by accident in 1975 when a fermentation stuck at Sutter Home — it went on to outsell red Zinfandel 6 to 1 and saved the old vines from being ripped out.",
      "Zinfandel can reach 16%+ alcohol naturally, making it one of the boldest table wines made."
    ]
  },
  {
    id: "sangiovese",
    name: "Sangiovese",
    pronounce: "san-joh-vay-zeh",
    category: "red",
    tagline: "The blood of Jove",
    hue: ["#8d2434", "#471019"],
    origin: "Tuscany, Italy (documented 1590)",
    regions: ["Chianti Classico", "Brunello di Montalcino", "Vino Nobile di Montepulciano", "Romagna", "Super Tuscan blends"],
    abv: "13–14.5%",
    sweetness: 0, body: 3, tannin: 4, acidity: 5,
    servingTemp: "16–18 °C (60–65 °F)",
    glassware: "Medium red wine glass",
    flavors: ["Sour cherry", "Red plum", "Tomato leaf", "Dried oregano", "Leather", "Espresso"],
    pairings: ["Pizza margherita", "Pasta with tomato ragù", "Bistecca alla fiorentina", "Pecorino", "Cured meats"],
    description: "Italy's most planted grape and the soul of Chianti and Brunello di Montalcino. High acid, firm tannin and sour-cherry fruit make Sangiovese the ultimate food wine — practically engineered for tomato-based Italian cooking.",
    facts: [
      "The name derives from Latin 'sanguis Jovis' — 'the blood of Jupiter'.",
      "Brunello di Montalcino must be 100% Sangiovese and aged at least five years before release — one of Italy's strictest wine laws.",
      "Chianti's famous straw-covered bottle is called a 'fiasco' — and yes, that's where the English word comes from.",
      "In 1716 Tuscany's Grand Duke Cosimo III legally defined the Chianti zone — one of the world's first protected wine appellations.",
      "The 'Super Tuscan' revolution of the 1970s (Tignanello, Sassicaia) began when producers broke Chianti's rules by blending Sangiovese with Cabernet — the wines got so famous the law changed instead."
    ]
  },
  {
    id: "tempranillo",
    name: "Tempranillo",
    pronounce: "tem-prah-nee-yoh",
    category: "red",
    tagline: "Spain's noble early ripener",
    hue: ["#701a2c", "#330a13"],
    origin: "Spain (grown since Phoenician times)",
    regions: ["Rioja", "Ribera del Duero", "Toro", "Portugal (as Tinta Roriz / Aragonez)"],
    abv: "13–14.5%",
    sweetness: 0, body: 4, tannin: 4, acidity: 3,
    servingTemp: "15–18 °C (59–64 °F)",
    glassware: "Standard red wine glass",
    flavors: ["Cherry", "Dried fig", "Dill", "Leather", "Tobacco", "Coconut & vanilla from American oak"],
    pairings: ["Roast lamb", "Jamón ibérico", "Manchego", "Paella", "Grilled vegetables"],
    description: "The great grape of Spain, named from 'temprano' (early) because it ripens weeks before its neighbours. In Rioja it's aged for years in American oak, emerging silky and laced with vanilla, dill and leather.",
    facts: [
      "Rioja's ageing categories are set by law: Crianza (2 years), Reserva (3 years) and Gran Reserva (5+ years, including 2 in barrel).",
      "Tempranillo goes by dozens of aliases: Tinto Fino, Tinta del País, Cencibel, Ull de Llebre ('hare's eye') and more.",
      "Rioja's love of American oak dates to the sherry trade — American barrels were cheaper and gave the wine its signature coconut-vanilla note.",
      "Phoenician traders were likely making wine from Tempranillo's ancestors in Spain 3,000 years ago.",
      "In Portugal's Douro Valley the same grape (as Tinta Roriz) is a key ingredient in Port."
    ]
  },
  {
    id: "nebbiolo",
    name: "Nebbiolo",
    pronounce: "neb-bee-oh-loh",
    category: "red",
    tagline: "Tar, roses and fog",
    hue: ["#9c3a38", "#54171c"],
    origin: "Piedmont, Italy (documented 1268)",
    regions: ["Barolo", "Barbaresco", "Langhe", "Valtellina (as Chiavennasca)", "Roero"],
    abv: "13.5–15%",
    sweetness: 0, body: 4, tannin: 5, acidity: 5,
    servingTemp: "16–18 °C (61–65 °F)",
    glassware: "Large Burgundy-style glass",
    flavors: ["Tar", "Rose", "Sour cherry", "Truffle", "Liquorice", "Dried herbs"],
    pairings: ["White truffle risotto", "Braised beef in Barolo", "Wild mushroom pasta", "Aged Parmigiano", "Game birds"],
    description: "The grape behind Barolo — 'the wine of kings and the king of wines'. Nebbiolo looks deceptively pale in the glass but hits with ferocious tannin and acidity, unfolding into haunting aromas of tar and roses that can take decades to fully emerge.",
    facts: [
      "The name comes from 'nebbia' — Italian for fog — the autumn mists that blanket Piedmont's hills when the grape is finally picked in late October.",
      "Barolo must age at least 38 months before release (62 for Riserva), among the longest legal minimums of any wine.",
      "Nebbiolo was documented by name in 1268, making it one of Italy's oldest recorded varieties.",
      "Until the 1850s Barolo was actually a sweet wine — the harvest was so late that cold winters stopped fermentation early.",
      "The classic tasting note 'tar and roses' is so iconic it became the title of a book about Piedmont's wines."
    ]
  },
  {
    id: "grenache",
    name: "Grenache / Garnacha",
    pronounce: "gruh-nash / gar-nah-cha",
    category: "red",
    tagline: "Sun-loving Mediterranean heart",
    hue: ["#a03045", "#5c1526"],
    origin: "Aragón, Spain",
    regions: ["Châteauneuf-du-Pape & Côtes du Rhône", "Priorat, Spain", "Sardinia (as Cannonau)", "McLaren Vale, Australia"],
    abv: "14–15.5%",
    sweetness: 0, body: 3, tannin: 2, acidity: 2,
    servingTemp: "15–17 °C (59–63 °F)",
    glassware: "Standard red wine glass",
    flavors: ["Strawberry", "Raspberry", "White pepper", "Dried herbs (garrigue)", "Orange peel", "Cinnamon"],
    pairings: ["Slow-roast pork", "Ratatouille", "Moroccan tagine", "Grilled chicken", "Spiced dishes"],
    description: "One of the world's most planted grapes and the fruity, spicy heart of Châteauneuf-du-Pape and countless Rhône and Spanish blends. Grenache loves heat and drought, thriving as gnarly old bush vines in the Mediterranean sun.",
    facts: [
      "Grenache is the 'G' in the classic 'GSM' blend — Grenache, Syrah, Mourvèdre.",
      "Châteauneuf-du-Pape ('the Pope's new castle') is named for the 14th-century popes who ruled from nearby Avignon and planted the vineyards.",
      "Sardinians credit their local Grenache, Cannonau, for the island's remarkable number of centenarians — it's unusually rich in antioxidant polyphenols.",
      "Its thin skins and pale colour mean Grenache is also the base of many of the world's finest rosés, including Tavel and much of Provence.",
      "Old bush-vine Grenache in Australia and Spain can be 100+ years old, producing tiny quantities of intensely concentrated wine."
    ]
  },
  {
    id: "barbera",
    name: "Barbera",
    pronounce: "bar-beh-rah",
    category: "red",
    tagline: "Piedmont's everyday joy",
    hue: ["#8b1e3f", "#420d1f"],
    origin: "Monferrato, Piedmont, Italy",
    regions: ["Barbera d'Asti", "Barbera d'Alba", "Nizza DOCG", "California (planted by Italian immigrants)"],
    abv: "13–14.5%",
    sweetness: 0, body: 3, tannin: 2, acidity: 5,
    servingTemp: "15–17 °C (59–63 °F)",
    glassware: "Medium red wine glass",
    flavors: ["Tart cherry", "Blackberry", "Plum", "Dried herbs", "Black pepper", "Espresso"],
    pairings: ["Salumi & antipasti", "Tajarin pasta", "Pizza", "Roast pork", "Mushroom dishes"],
    description: "While Nebbiolo gets the glory in Piedmont, Barbera is what the locals actually drink with dinner. Deep purple colour, juicy dark fruit, almost no tannin and mouth-watering acidity make it one of Italy's great food wines.",
    facts: [
      "Barbera is Piedmont's most planted grape — roughly a third of the region's vineyards.",
      "It's unusual among reds: very high acidity but very low tannin, the opposite of its neighbour Nebbiolo.",
      "Nizza, carved out as its own DOCG in 2014, is Barbera's grand-cru-level appellation.",
      "Italian immigrants took Barbera to California and Argentina in the 19th century, where old plantings survive today.",
      "Traditionally the grape was so associated with the working class that ordering 'a Barbera' simply meant ordering a glass of red."
    ]
  },
  {
    id: "cabernet-franc",
    name: "Cabernet Franc",
    pronounce: "kab-er-nay frahnk",
    category: "red",
    tagline: "The elegant parent",
    hue: ["#7c2135", "#3c0e19"],
    origin: "Basque Country / Bordeaux, France",
    regions: ["Loire Valley (Chinon, Bourgueil)", "Saint-Émilion, Bordeaux", "Niagara, Canada", "Finger Lakes, USA", "Argentina"],
    abv: "12.5–14%",
    sweetness: 0, body: 3, tannin: 3, acidity: 4,
    servingTemp: "14–17 °C (57–63 °F)",
    glassware: "Bordeaux glass",
    flavors: ["Raspberry", "Redcurrant", "Bell pepper", "Crushed gravel", "Violet", "Chilli flake"],
    pairings: ["Roast turkey", "Lentil dishes", "Goat's cheese", "Herb-crusted lamb", "Charcuterie"],
    description: "The genetic parent of both Cabernet Sauvignon and Merlot, Cabernet Franc is lighter, leafier and more perfumed than either child. In the Loire Valley it makes silky, peppery reds; in Bordeaux it adds fragrance to the great blends of Saint-Émilion.",
    facts: [
      "Cabernet Franc is a parent of Cabernet Sauvignon, Merlot AND Carménère — making it the patriarch of the whole Bordeaux family.",
      "Cheval Blanc, one of Bordeaux's most celebrated châteaux, is built primarily on Cabernet Franc.",
      "Its signature bell-pepper note comes from pyrazine compounds that diminish as the grape ripens.",
      "Because it buds early and ripens early, it thrives in cool regions where Cabernet Sauvignon fails — like Canada and the Loire.",
      "Cardinal Richelieu is credited with spreading the grape to the Loire in the 17th century, where it was named 'Breton'."
    ]
  },
  {
    id: "gamay",
    name: "Gamay (Beaujolais)",
    pronounce: "gam-ay",
    category: "red",
    tagline: "The joyful glugger",
    hue: ["#b03a55", "#6b1830"],
    origin: "Burgundy, France (village of Gamay, 14th century)",
    regions: ["Beaujolais (10 crus incl. Morgon, Fleurie)", "Loire Valley", "Switzerland", "Niagara, Canada"],
    abv: "12–13.5%",
    sweetness: 0, body: 2, tannin: 1, acidity: 4,
    servingTemp: "12–14 °C (54–57 °F) — lightly chilled!",
    glassware: "Standard red or Burgundy glass",
    flavors: ["Fresh cranberry", "Cherry", "Banana (nouveau style)", "Violet", "Peony", "Crushed stone"],
    pairings: ["Charcuterie", "Roast chicken", "Thanksgiving dinner", "Soft cheeses", "Picnic food"],
    description: "The happy grape of Beaujolais: light, fresh, floral and made to be drunk young, often lightly chilled. Beneath the party reputation of Beaujolais Nouveau lie ten serious 'cru' villages making structured, age-worthy wines.",
    facts: [
      "In 1395 Duke Philip the Bold of Burgundy banned the 'disloyal' Gamay from Burgundy's best land, exiling it south to Beaujolais — the best thing that ever happened to it.",
      "Beaujolais Nouveau is released at 12:01 am on the third Thursday of November, weeks after harvest, with races historically run to get the first bottles to Paris.",
      "The banana and bubble-gum aromas in Nouveau come from carbonic maceration — whole bunches fermenting from the inside out under a blanket of CO₂.",
      "At its 1980s peak, over half of all Beaujolais was sold as Nouveau.",
      "Cru Beaujolais from villages like Morgon can age ten years and be mistaken for fine Burgundy — locals say old Morgon 'pinotes' (turns Pinot-like)."
    ]
  },
  {
    id: "carmenere",
    name: "Carménère",
    pronounce: "kar-men-nair",
    category: "red",
    tagline: "The lost grape of Bordeaux",
    hue: ["#5f1430", "#280818"],
    origin: "Bordeaux, France; rediscovered in Chile",
    regions: ["Colchagua & Maipo Valleys, Chile", "small plantings in Italy and China"],
    abv: "13–14.5%",
    sweetness: 0, body: 4, tannin: 3, acidity: 3,
    servingTemp: "15–18 °C (59–64 °F)",
    glassware: "Bordeaux glass",
    flavors: ["Black plum", "Raspberry", "Green peppercorn", "Paprika", "Cocoa", "Soy-like umami"],
    pairings: ["Roast pork", "Grilled vegetables", "Beef stir-fry", "Mole dishes", "Empanadas"],
    description: "A Bordeaux grape presumed extinct after the 19th-century phylloxera plague — until 1994, when a scientist realised Chile's 'Merlot' vines were actually Carménère. Chile now treats the herbal, plummy grape as its national signature.",
    facts: [
      "For over a century Chilean growers unknowingly sold Carménère as Merlot; DNA testing by Jean-Michel Boursiquot revealed the truth in 1994.",
      "Chile's isolation (desert, Andes, ocean, Antarctic) kept phylloxera out — its vines grow on their own original roots, almost unique in the wine world.",
      "The name comes from 'carmin', the crimson colour of its autumn leaves.",
      "24 November is celebrated as International Carménère Day, marking the 1994 rediscovery.",
      "Under-ripe Carménère tastes distinctly of green pepper and soy; fully ripe, it shifts to plum and chocolate — timing the harvest is everything."
    ]
  },
  {
    id: "pinotage",
    name: "Pinotage",
    pronounce: "pee-noh-tahj",
    category: "red",
    tagline: "South Africa's bold invention",
    hue: ["#5a1226", "#250712"],
    origin: "Stellenbosch, South Africa (1925)",
    regions: ["Stellenbosch", "Swartland", "Paarl", "small plantings in NZ and California"],
    abv: "13.5–15%",
    sweetness: 0, body: 4, tannin: 4, acidity: 3,
    servingTemp: "15–18 °C (59–64 °F)",
    glassware: "Standard red wine glass",
    flavors: ["Black plum", "Smoked bacon", "Sweet pipe tobacco", "Rooibos", "Blackberry", "Coffee & dark chocolate (modern styles)"],
    pairings: ["Braai (South African barbecue)", "Venison", "Bobotie", "Ribs with sticky sauce", "Smoked meats"],
    description: "Created in 1925 by Stellenbosch professor Abraham Perold, Pinotage is a cross of Pinot Noir and Cinsault. Smoky, brambly and unapologetically bold, it is South Africa's signature grape — divisive, distinctive and increasingly refined.",
    facts: [
      "Perold crossed Pinot Noir with Cinsault (then locally called 'Hermitage') — hence Pino-tage.",
      "The four original seedlings were nearly lost: they were rescued from Perold's abandoned garden by a young lecturer just before the plot was cleared.",
      "The first commercial Pinotage vintage wasn't until 1941 — sixteen years after the cross was made.",
      "Trendy 'coffee Pinotage' styles use heavy toasted oak to amplify natural mocha notes, and have converted a generation of new drinkers.",
      "Pinotage is a required component (30–70%) of South Africa's official 'Cape Blend' category."
    ]
  },
  {
    id: "mourvedre",
    name: "Mourvèdre / Monastrell",
    pronounce: "moor-ved-ruh / moh-nah-strel",
    category: "red",
    tagline: "The wild, meaty one",
    hue: ["#4a0f22", "#1d0510"],
    origin: "Valencia region, Spain",
    regions: ["Bandol, France", "Jumilla & Yecla, Spain", "Rhône blends", "California & Australia (as Mataro)"],
    abv: "14–15.5%",
    sweetness: 0, body: 5, tannin: 5, acidity: 3,
    servingTemp: "16–18 °C (61–65 °F)",
    glassware: "Large red wine glass",
    flavors: ["Blackberry", "Black pepper", "Roast meat", "Leather", "Wild herbs", "Violet"],
    pairings: ["Game", "Lamb shoulder", "Beef stew", "Hard aged cheeses", "Wild boar ragù"],
    description: "A heat-loving Spanish grape that produces dense, dark, gamey wines. It is the backbone of Bandol in Provence and the 'M' in GSM blends, famous for aromas that tasters politely call 'animal'.",
    facts: [
      "Growers say Mourvèdre likes 'its face in the sun and its feet in the water' — it needs both heat and deep moisture to ripen.",
      "In Bandol, wines must contain at least 50% Mourvèdre and age 18 months in barrel.",
      "Australians and Californians long knew it as 'Mataro' before the French name became fashionable.",
      "Its naturally high tannin and antioxidant levels make it one of the longest-lived Mediterranean reds.",
      "Jumilla in Spain has vast plantings of old, own-rooted (ungrafted) Monastrell that survived phylloxera in the sandy soils."
    ]
  },
  {
    id: "petite-sirah",
    name: "Petite Sirah",
    pronounce: "puh-teet sih-rah",
    category: "red",
    tagline: "Small grape, giant wine",
    hue: ["#3d0a24", "#160411"],
    origin: "France (as Durif, 1860s); adopted by California",
    regions: ["California (Lodi, Napa, Mendocino)", "Israel", "Australia (as Durif)", "Mexico"],
    abv: "13.5–15.5%",
    sweetness: 0, body: 5, tannin: 5, acidity: 3,
    servingTemp: "16–18 °C (61–65 °F)",
    glassware: "Large red wine glass",
    flavors: ["Blueberry", "Dark chocolate", "Black tea", "Black pepper", "Plum sauce", "Espresso"],
    pairings: ["Beef short ribs", "Barbecue", "Blue cheese burgers", "Mole poblano", "Braised oxtail"],
    description: "Despite the name, nothing about the wine is petite — only the berries are small, giving a huge skin-to-juice ratio and some of the inkiest, most tannic wines made anywhere. A Californian favourite for adding 'backbone' to blends.",
    facts: [
      "Petite Sirah is actually the grape Durif — a cross of Syrah and the obscure Peloursin, bred by Dr François Durif in the 1860s.",
      "The wine is so darkly pigmented it can literally stain teeth purple after a glass or two.",
      "Its tiny berries mean more skin per drop of juice — hence the massive colour and tannin.",
      "California has celebrated it since the 1880s; some 'mixed black' heritage vineyards still interplant it with Zinfandel.",
      "Fan clubs exist: 'P.S. I Love You' is a real advocacy organisation devoted solely to Petite Sirah."
    ]
  },

  // ================= WHITE WINES =================
  {
    id: "chardonnay",
    name: "Chardonnay",
    pronounce: "shar-doh-nay",
    category: "white",
    tagline: "The world's chameleon white",
    hue: ["#f3d98a", "#d9ae4e"],
    origin: "Burgundy, France (village of Chardonnay)",
    regions: ["Chablis & Côte de Beaune, Burgundy", "Champagne", "California", "Margaret River & Yarra, Australia", "Chile & South Africa"],
    abv: "12.5–14.5%",
    sweetness: 0, body: 4, tannin: 0, acidity: 3,
    servingTemp: "10–13 °C (50–55 °F)",
    glassware: "Wide-bowled white wine glass",
    flavors: ["Green apple (cool climate)", "Lemon curd", "Pineapple (warm climate)", "Butter", "Toasted brioche", "Hazelnut & vanilla from oak"],
    pairings: ["Roast chicken", "Lobster with butter", "Creamy pasta", "Brie", "Popcorn (seriously — with oaked styles)"],
    description: "The world's most famous white grape and its greatest shape-shifter: steely and mineral in Chablis, rich and buttery in California, and the backbone of Blanc de Blancs Champagne. Chardonnay reflects winemaking choices — oak, lees, malolactic — more than almost any other grape.",
    facts: [
      "Chardonnay is a natural cross of Pinot Noir and the ancient grape Gouais Blanc — a peasant grape once banned in medieval France.",
      "The 'buttery' flavour comes from malolactic conversion, which turns sharp malic acid into creamy lactic acid and produces the butter molecule diacetyl.",
      "Chablis vineyards grow on Kimmeridgian limestone packed with 150-million-year-old fossilised oyster shells.",
      "The 'ABC' movement ('Anything But Chardonnay') of the 1990s was a backlash against over-oaked styles — modern winemaking has swung back to freshness.",
      "It's one of the three Champagne grapes, and 100% Chardonnay Champagne is labelled 'Blanc de Blancs' (white from whites)."
    ]
  },
  {
    id: "sauvignon-blanc",
    name: "Sauvignon Blanc",
    pronounce: "soh-vin-yon blahnk",
    category: "white",
    tagline: "Zesty, grassy, electric",
    hue: ["#e9e7a8", "#c8cc6b"],
    origin: "Loire Valley / Bordeaux, France",
    regions: ["Marlborough, NZ", "Sancerre & Pouilly-Fumé, Loire", "Bordeaux", "Chile (Casablanca)", "South Africa"],
    abv: "12–13.5%",
    sweetness: 0, body: 2, tannin: 0, acidity: 5,
    servingTemp: "7–10 °C (45–50 °F)",
    glassware: "Narrow white wine glass",
    flavors: ["Gooseberry", "Passion fruit", "Cut grass", "Lime", "Bell pepper", "Flint (Loire styles)"],
    pairings: ["Goat's cheese", "Oysters", "Asparagus", "Thai salads", "Ceviche"],
    description: "The wake-up call of white wines — piercingly aromatic, grassy and citrusy with electric acidity. New Zealand's Marlborough region reinvented the grape in the 1980s and turned it into a global phenomenon.",
    facts: [
      "The name means 'wild white' (sauvage + blanc) — it was found growing wild in south-west France.",
      "Its signature aromas come from methoxypyrazines (green/grassy) and thiols (passion fruit/grapefruit) — among the most studied aroma compounds in wine science.",
      "Marlborough planted its first Sauvignon Blanc only in 1973; fifty years later it accounts for over 85% of New Zealand's wine exports.",
      "Sancerre and Pouilly-Fumé — the grape's Loire heartland — sit almost exactly on the same latitude as Marlborough's antipode in the opposite hemisphere.",
      "Sauvignon Blanc is a parent of Cabernet Sauvignon, after a chance vineyard fling with Cabernet Franc centuries ago."
    ]
  },
  {
    id: "riesling",
    name: "Riesling",
    pronounce: "reece-ling",
    category: "white",
    tagline: "The aromatic tightrope walker",
    hue: ["#f0e9ae", "#d9c455"],
    origin: "Rhine region, Germany (documented 1435)",
    regions: ["Mosel & Rheingau, Germany", "Alsace, France", "Clare & Eden Valleys, Australia", "Finger Lakes, USA", "Austria"],
    abv: "8–13%",
    sweetness: 2, body: 2, tannin: 0, acidity: 5,
    servingTemp: "7–11 °C (45–52 °F)",
    glassware: "Tall, slim white wine glass",
    flavors: ["Lime", "Green apple", "Apricot", "Honeysuckle", "Beeswax", "Petrol/kerosene (with age)"],
    pairings: ["Thai & Vietnamese food", "Spicy curries", "Pork belly", "Duck", "Apple desserts (sweet styles)"],
    description: "Wine critics' favourite white grape: capable of everything from bone-dry to gloriously sweet, always balanced on a wire of scintillating acidity. Great Riesling can age 50+ years and transmits its vineyard like a radio signal.",
    facts: [
      "Aged Riesling famously smells of petrol — caused by the compound TDN, and prized (in moderation) by connoisseurs.",
      "In 1775 the courier carrying harvest permission to Schloss Johannisberg arrived weeks late; the rotted grapes accidentally created the great Spätlese (late harvest) tradition.",
      "Riesling was once more expensive than the top wines of Bordeaux — German Rieslings led global price lists in the 1900s.",
      "The Mosel's slate slopes are so steep (up to 65°) that workers harvest with ropes and winches.",
      "German label terms (Kabinett, Spätlese, Auslese…) rank ripeness at harvest, not sweetness in the bottle — a dry Spätlese is entirely possible."
    ]
  },
  {
    id: "pinot-grigio",
    name: "Pinot Grigio / Pinot Gris",
    pronounce: "pee-noh gree-joh / gree",
    category: "white",
    tagline: "Two grapes in one skin",
    hue: ["#f2e3b0", "#dcbd7a"],
    origin: "Burgundy/Alsace (a mutation of Pinot Noir)",
    regions: ["Veneto & Friuli, Italy", "Alsace, France", "Oregon, USA", "New Zealand", "Germany (as Grauburgunder)"],
    abv: "12–14%",
    sweetness: 1, body: 2, tannin: 0, acidity: 4,
    servingTemp: "7–10 °C (45–50 °F)",
    glassware: "Standard white wine glass",
    flavors: ["Lemon", "Green pear", "White peach", "Almond", "Honey & ginger (Alsace style)", "Wet stone"],
    pairings: ["Light seafood", "Antipasti", "Sushi", "Salads", "Roast pork (Alsace styles)"],
    description: "The same grape wears two costumes: Italian 'Pinot Grigio' is light, crisp and citrusy — the world's favourite easy white — while Alsatian 'Pinot Gris' is rich, spicy and honeyed. Its greyish-pink skins give both their subtle coppery glint.",
    facts: [
      "'Grigio'/'Gris' means grey — the grapes are actually greyish-pink to brownish-blue, not green.",
      "It is a colour mutation of Pinot Noir: genetically the two are essentially identical.",
      "Pinot Grigio became Italy's biggest white wine export, with the delle Venezie region producing hundreds of millions of bottles a year.",
      "Because the skins carry colour, extended skin contact makes 'ramato' (coppery) wines — a traditional Friulian style that is essentially a light orange wine.",
      "In the 1800s it was known in Germany as 'Ruländer', named after a merchant, Johann Ruland, who found the vines growing wild in an abandoned garden."
    ]
  },
  {
    id: "gewurztraminer",
    name: "Gewürztraminer",
    pronounce: "guh-vurts-trah-mee-ner",
    category: "white",
    tagline: "Lychee and roses in a glass",
    hue: ["#f4d791", "#e0ab52"],
    origin: "Tramin, Alto Adige (Italy) / perfected in Alsace",
    regions: ["Alsace, France", "Alto Adige, Italy", "Germany", "New Zealand", "Washington State"],
    abv: "13–14.5%",
    sweetness: 2, body: 4, tannin: 0, acidity: 1,
    servingTemp: "8–11 °C (46–52 °F)",
    glassware: "Aromatic white wine glass",
    flavors: ["Lychee", "Rose petal", "Ginger", "Turkish delight", "Grapefruit", "Allspice"],
    pairings: ["Munster cheese", "Indian curries", "Sichuan dishes", "Foie gras", "Gingerbread"],
    description: "The most flamboyantly perfumed grape in the world — a single sniff of lychee and rose petals identifies it instantly. 'Gewürz' means 'spice' in German, and in Alsace it makes golden, opulent, gently sweet wines.",
    facts: [
      "Its lychee aroma is chemistry, not fancy: the wine and the fruit share the exact aroma compound (cis-rose oxide).",
      "The grape's skins are pink, so the wine is often deep gold with a coppery tinge.",
      "It's a spicier, aromatic mutation of the ancient grape Savagnin (Traminer), named after the village of Tramin in the Italian Alps.",
      "Gewürztraminer is famously low in acid and high in alcohol — the opposite of Riesling, its Alsatian neighbour.",
      "Alsace classifies it as one of only four 'noble grapes' allowed in its Grand Cru vineyards."
    ]
  },
  {
    id: "chenin-blanc",
    name: "Chenin Blanc",
    pronounce: "shen-in blahnk",
    category: "white",
    tagline: "The honeyed all-rounder",
    hue: ["#f1e08e", "#d9b74e"],
    origin: "Loire Valley, France (9th century)",
    regions: ["Vouvray & Savennières, Loire", "South Africa (as Steen)", "California", "Argentina"],
    abv: "11.5–14%",
    sweetness: 2, body: 3, tannin: 0, acidity: 5,
    servingTemp: "8–12 °C (46–54 °F)",
    glassware: "Standard white wine glass",
    flavors: ["Quince", "Baked apple", "Honey", "Chamomile", "Wet wool (a classic!)", "Ginger"],
    pairings: ["Pork with apples", "Roast chicken", "Soft-ripened cheeses", "Thai green curry (off-dry)", "Tarte tatin (sweet styles)"],
    description: "The Loire's Swiss-army-knife grape: it makes bone-dry whites, sparkling Crémant, off-dry charmers and some of the world's longest-lived sweet wines — all with a core of honeyed fruit and racy acidity.",
    facts: [
      "South Africa has more Chenin Blanc than the rest of the world combined — it arrived with Dutch settlers in 1655.",
      "Sweet Vouvray and Quarts de Chaume can age for a century; some 1940s bottles still taste fresh.",
      "In South Africa it was long called 'Steen' and its true identity was only confirmed in 1965.",
      "Chenin's naturally ferocious acidity means even lusciously sweet versions never taste cloying.",
      "Savennières, the great dry Chenin appellation, was a favourite of writer Curnonsky, who called it one of France's five greatest whites."
    ]
  },
  {
    id: "viognier",
    name: "Viognier",
    pronounce: "vee-oh-nyay",
    category: "white",
    tagline: "Apricots and springtime",
    hue: ["#f5d98d", "#e3b355"],
    origin: "Northern Rhône, France",
    regions: ["Condrieu, Rhône", "Languedoc", "California", "Australia", "Virginia, USA"],
    abv: "13.5–15%",
    sweetness: 0, body: 4, tannin: 0, acidity: 2,
    servingTemp: "9–12 °C (48–54 °F)",
    glassware: "Wide aromatic white glass",
    flavors: ["Apricot", "Peach", "Honeysuckle", "Tangerine", "Crème brûlée", "White pepper"],
    pairings: ["Scallops", "Lobster bisque", "Roast pumpkin", "Mild curries", "Soft cheeses"],
    description: "A hedonist's white: heady apricot and honeysuckle perfume wrapped in a rich, oily texture. Viognier nearly went extinct in the 1960s — only about 30 acres survived in Condrieu — before a spectacular global revival.",
    facts: [
      "By 1965 there were just 8–14 hectares of Viognier left on Earth; today there are over 15,000.",
      "In Côte-Rôtie, up to 20% Viognier may legally be co-fermented into the red Syrah — a white grape in a famous red wine.",
      "Condrieu, its tiny homeland, makes only white wine, and virtually all of it is Viognier.",
      "The grape must be picked fully ripe to develop its perfume — pick early and it tastes of nothing, late and it turns flabby. Growers call the window 'a knife's edge'.",
      "Virginia in the USA adopted Viognier as its official state grape in 2011."
    ]
  },
  {
    id: "albarino",
    name: "Albariño",
    pronounce: "al-bah-reen-yoh",
    category: "white",
    tagline: "The wine of the sea",
    hue: ["#eeeaa4", "#cfd06a"],
    origin: "Rías Baixas, Galicia, Spain",
    regions: ["Rías Baixas, Spain", "Vinho Verde, Portugal (as Alvarinho)", "California", "Uruguay"],
    abv: "11.5–13%",
    sweetness: 0, body: 2, tannin: 0, acidity: 5,
    servingTemp: "7–10 °C (45–50 °F)",
    glassware: "Standard white wine glass",
    flavors: ["Lemon zest", "White peach", "Nectarine", "Sea spray salinity", "Grapefruit", "Wet stone"],
    pairings: ["Grilled sardines", "Octopus (pulpo a la gallega)", "Clams", "Padrón peppers", "Sushi"],
    description: "Grown within sight of the Atlantic on Spain's green Galician coast, Albariño is the ultimate seafood white — saline, peachy and mouth-wateringly fresh, traditionally trained high on granite pergolas above the damp ground.",
    facts: [
      "Galician vines are trained on stone-pillared pergolas ('parras') up to head height, to beat the Atlantic damp and mildew.",
      "The name likely means 'little white one from the Rhine' — a legend claims monks brought it via the Camino de Santiago, though DNA says it's local.",
      "Tasters swear great Albariño tastes literally salty — the vineyards are sprayed by ocean mist.",
      "Rías Baixas ('the lower estuaries') is named for its fjord-like drowned river valleys.",
      "Across the river in Portugal the same grape, Alvarinho, makes the most serious versions of Vinho Verde."
    ]
  },
  {
    id: "gruner-veltliner",
    name: "Grüner Veltliner",
    pronounce: "groo-ner velt-lee-ner",
    category: "white",
    tagline: "Austria's peppery pride",
    hue: ["#ecefa9", "#c3ce6c"],
    origin: "Austria (Danube valleys)",
    regions: ["Wachau, Kamptal & Kremstal, Austria", "Czechia & Slovakia", "small US and NZ plantings"],
    abv: "11.5–13.5%",
    sweetness: 0, body: 3, tannin: 0, acidity: 4,
    servingTemp: "8–11 °C (46–52 °F)",
    glassware: "Standard white wine glass",
    flavors: ["White pepper", "Green apple", "Radish", "Lentil", "Lime", "Snap pea"],
    pairings: ["Wiener schnitzel", "Asparagus (its famous ally)", "Sushi", "Green salads", "Fried chicken"],
    description: "Austria's flagship grape — almost a third of the country's vineyards — making zippy whites with a signature dusting of white pepper. It has a party trick: it pairs with 'difficult' vegetables like asparagus and artichoke that clash with most wines.",
    facts: [
      "In a famous 2002 London blind tasting, top Grüner Veltliners beat grand cru white Burgundies — instantly making the grape fashionable worldwide.",
      "Its white-pepper bite comes from rotundone, the same compound found in Syrah and actual peppercorns.",
      "Wachau growers use a unique ripeness ranking: Steinfeder, Federspiel and Smaragd — the last named after an emerald lizard that suns itself in the vineyards.",
      "It's affectionately nicknamed 'Grü-Vee' in the United States.",
      "One parent is the ancient Traminer; the other, St. Georgen, was identified from a single surviving 400-year-old vine found near a village in Burgenland."
    ]
  },
  {
    id: "semillon",
    name: "Sémillon",
    pronounce: "seh-mee-yon",
    category: "white",
    tagline: "The quiet achiever",
    hue: ["#f2dc8f", "#dfb95b"],
    origin: "Bordeaux, France",
    regions: ["Sauternes & Graves, Bordeaux", "Hunter Valley, Australia", "Barossa", "Washington State", "South Africa"],
    abv: "10.5–14%",
    sweetness: 0, body: 3, tannin: 0, acidity: 3,
    servingTemp: "8–12 °C (46–54 °F)",
    glassware: "Standard white wine glass",
    flavors: ["Lemon", "Lanolin", "Beeswax", "Green papaya", "Toast (with age)", "Honey"],
    pairings: ["Fish and chips", "Roast chicken", "Crab", "Comté cheese", "Chicken pie"],
    description: "Bordeaux's under-sung white grape: waxy, gentle and long-lived. In Hunter Valley, Australia, it performs a magic trick — picked early at barely 10.5% alcohol, it starts life neutral and evolves over decades into honeyed, toasty splendour.",
    facts: [
      "Sémillon is the main grape of Sauternes, the world's most famous sweet wine, thanks to its thin skin welcoming noble rot.",
      "Aged Hunter Valley Sémillon tastes toasty and oaked — yet traditionally never sees a single oak barrel.",
      "In the 1820s Sémillon covered a huge share of South Africa's vineyards and was simply called 'wyndruif' — 'wine grape'.",
      "It's usually blended with Sauvignon Blanc, adding waxy weight to the latter's zing — the classic white Bordeaux formula.",
      "Its name may derive from 'semaine' (week) — supposedly for the saint's week when it was traditionally picked."
    ]
  },
  {
    id: "moscato",
    name: "Muscat / Moscato",
    pronounce: "muhs-kat / mos-kah-toh",
    category: "white",
    tagline: "The grape that tastes of grapes",
    hue: ["#f6e394", "#e6c257"],
    origin: "Ancient Greece / Mediterranean — possibly the oldest domesticated wine grape",
    regions: ["Asti, Piedmont (Moscato d'Asti)", "Alsace", "Rutherglen, Australia", "Greece (Samos)", "South of France (Beaumes-de-Venise)"],
    abv: "5.5–13%",
    sweetness: 4, body: 2, tannin: 0, acidity: 3,
    servingTemp: "6–8 °C (43–46 °F)",
    glassware: "Small white or flute (for Moscato d'Asti)",
    flavors: ["Grape (the only wine that really does!)", "Orange blossom", "Peach", "Honeysuckle", "Ginger", "Rose"],
    pairings: ["Fruit tarts", "Brunch pastries", "Spicy Asian food (off-dry)", "Pavlova", "Blue cheese (sweet fortified styles)"],
    description: "The Muscat family is probably the oldest of all wine grapes — and famously the only one whose wine actually smells of the fresh grape itself. Its most loved form is Moscato d'Asti: gently fizzy, softly sweet and only about 5.5% alcohol.",
    facts: [
      "Muscat is a family of over 200 related varieties; Muscat Blanc à Petits Grains is the noblest.",
      "The distinctive grapey perfume comes from linalool — the same terpene found in lavender and coriander.",
      "The ancient Greeks and Romans drank Muscat; some historians believe it's the oldest domesticated wine grape on Earth.",
      "Moscato d'Asti's fermentation is stopped early by chilling, keeping the wine sweet, lightly fizzy ('frizzante') and low-alcohol.",
      "Moscato had an unlikely 2010s boom when American hip-hop artists began name-checking it — US sales exploded by over 70% in a single year."
    ]
  },
  {
    id: "torrontes",
    name: "Torrontés",
    pronounce: "tor-ron-tez",
    category: "white",
    tagline: "Argentina's perfumed native",
    hue: ["#f2e59c", "#d9c161"],
    origin: "Argentina (a natural New World cross)",
    regions: ["Salta (Cafayate)", "La Rioja, Argentina", "Mendoza"],
    abv: "12.5–14%",
    sweetness: 0, body: 2, tannin: 0, acidity: 3,
    servingTemp: "7–10 °C (45–50 °F)",
    glassware: "Aromatic white wine glass",
    flavors: ["Rose petal", "Geranium", "White peach", "Lemon zest", "Lychee", "Fresh herbs"],
    pairings: ["Ceviche", "Empanadas", "Thai food", "Soft cheeses", "Grilled fish with salsa verde"],
    description: "Argentina's only truly native fine-wine grape — smelling sweetly of roses and peaches but finishing crisp and dry. Its best examples grow in Cafayate at dizzying altitudes where intense sun and cool nights concentrate the perfume.",
    facts: [
      "DNA shows Torrontés is a natural cross of Muscat of Alexandria and the Mission grape — both brought by Spanish missionaries.",
      "There are three Argentine Torrontés varieties: Riojano (the best), Sanjuanino and Mendocino.",
      "Cafayate's vineyards sit at ~1,700–3,000 m — among the highest on Earth — under some of the most intense sunlight of any wine region.",
      "The rose-like aroma fools many tasters into expecting a sweet wine; classic Torrontés is bone dry.",
      "Despite the shared name, it is unrelated to Spain's Torrontés grapes — the Argentine one is its own creation."
    ]
  },
  {
    id: "verdejo",
    name: "Verdejo",
    pronounce: "ver-day-ho",
    category: "white",
    tagline: "Castile's bitter-almond charmer",
    hue: ["#edeb9f", "#c9cd68"],
    origin: "Rueda, Spain (possibly via North Africa, 11th century)",
    regions: ["Rueda, Spain"],
    abv: "12–13.5%",
    sweetness: 0, body: 2, tannin: 0, acidity: 4,
    servingTemp: "7–10 °C (45–50 °F)",
    glassware: "Standard white wine glass",
    flavors: ["Lime", "Fennel", "White peach", "Bitter almond", "Fresh-cut grass", "Grapefruit pith"],
    pairings: ["Tapas", "Grilled white fish", "Manchego", "Garlic prawns", "Green salads"],
    description: "The zesty white of Spain's high Castilian plateau, with a signature bitter-almond twist on the finish. Verdejo was rescued from obscurity in the 1970s and is now one of Spain's most popular whites.",
    facts: [
      "Verdejo likely arrived in Rueda with Mozarabic settlers around the 11th century, possibly from North Africa.",
      "For centuries it was used for a sherry-like oxidised wine called 'Dorado'; the fresh modern style dates only from the 1970s, when the Rioja house Marqués de Riscal helped pioneer cold fermentation there.",
      "The name comes from 'verde' (green), for the grape's colour.",
      "Rueda's extreme continental climate — baking days, freezing nights — preserves the grape's acidity; harvest is often done at night by machine to keep the fruit cool.",
      "Its grassy-citrus style is so Sauvignon-like that the two are often blended in Rueda."
    ]
  },
  {
    id: "vermentino",
    name: "Vermentino",
    pronounce: "ver-men-tee-noh",
    category: "white",
    tagline: "The Mediterranean beach white",
    hue: ["#f0eca6", "#d2cf70"],
    origin: "Italian/French Mediterranean coast (Liguria, Sardinia, Corsica)",
    regions: ["Sardinia (Gallura)", "Liguria & Tuscany, Italy", "Corsica & Provence (as Rolle)", "Australia"],
    abv: "12.5–14%",
    sweetness: 0, body: 3, tannin: 0, acidity: 4,
    servingTemp: "8–11 °C (46–52 °F)",
    glassware: "Standard white wine glass",
    flavors: ["Lime", "Green apple", "Salt spray", "Almond", "Wild herbs", "Grapefruit"],
    pairings: ["Seafood pasta", "Grilled fish", "Pesto dishes", "Fritto misto", "Salads"],
    description: "The sun-and-sea white of the Italian and French Rivieras — crisp, saline and herb-tinged, with a gently bitter almond finish. It's the taste of a Mediterranean beach holiday in a glass.",
    facts: [
      "Sardinia's Vermentino di Gallura is the island's only DOCG (top-tier) wine, grown on wind-blasted granite.",
      "In Provence and Corsica the same grape is called 'Rolle' and stars in many rosé blends.",
      "The classic slightly bitter finish is prized by Italians — 'ammandorlato', meaning almond-like.",
      "Vermentino resists drought and sea wind superbly, making it a climate-change favourite; Australian growers have embraced it for exactly this reason.",
      "Its origins are argued over by Italy, France and Spain — DNA links it to grapes grown across the whole western Mediterranean."
    ]
  },

  // ================= ROSÉ WINES =================
  {
    id: "provence-rose",
    name: "Provence Rosé",
    pronounce: "pro-vahnss ro-zay",
    category: "rose",
    tagline: "The pale pink original",
    hue: ["#f6c9b8", "#eda28e"],
    origin: "Provence, France (wine made here for 2,600 years)",
    regions: ["Côtes de Provence", "Bandol", "Coteaux d'Aix-en-Provence"],
    abv: "12–13.5%",
    sweetness: 0, body: 2, tannin: 1, acidity: 4,
    servingTemp: "8–10 °C (46–50 °F)",
    glassware: "Standard white wine glass",
    flavors: ["Strawberry", "White peach", "Melon", "Rose petal", "Celery salt", "Citrus zest"],
    pairings: ["Niçoise salad", "Grilled prawns", "Bouillabaisse", "Goat's cheese", "Anything by a pool"],
    description: "The world's benchmark rosé: barely-pink, bone dry, delicate and dangerously drinkable. Provence is the oldest wine region in France — the Greeks planted vines at Marseille around 600 BC, and the first wines were probably pink.",
    facts: [
      "Rosé is likely the oldest style of wine — ancient reds were pressed quickly and pale, essentially rosés.",
      "Provence produces around 90% of its wine as rosé — no other major region is so specialised.",
      "The pale colour comes from just 2–12 hours of skin contact before the juice is drained off.",
      "Rosé outsells white wine in France, and has done since 2008.",
      "Provence's official colour palette for rosé includes named shades like 'peach', 'melon', 'mango', 'mandarin', 'redcurrant' and 'marble pink' — judged against a colour wheel."
    ]
  },
  {
    id: "white-zinfandel",
    name: "White Zinfandel",
    pronounce: "wite zin-fan-del",
    category: "rose",
    tagline: "The happy accident",
    hue: ["#f5b3c0", "#eb8099"],
    origin: "Sutter Home winery, California, 1975",
    regions: ["California (Central Valley, Lodi)"],
    abv: "8.5–10.5%",
    sweetness: 3, body: 2, tannin: 0, acidity: 3,
    servingTemp: "6–8 °C (43–46 °F)",
    glassware: "Standard white wine glass",
    flavors: ["Strawberry candy", "Watermelon", "Cotton candy", "Peach", "Sweet citrus", "Melon"],
    pairings: ["Spicy wings", "Barbecue chicken", "Fruit salads", "Mild curries", "Picnic food"],
    description: "Wine snobs sneer, but White Zinfandel is a genuine piece of wine history: a stuck fermentation at Sutter Home in 1975 accidentally created a sweet pink wine that became an American phenomenon — and saved California's precious old Zinfandel vines from being ripped out.",
    facts: [
      "Winemaker Bob Trinchero's 1975 batch of pink Zinfandel stopped fermenting with sugar left over; he bottled it anyway — and created a legend.",
      "At its peak, White Zinfandel outsold red Zinfandel six bottles to one.",
      "The style is credited with keeping demand alive for old-vine Zinfandel vineyards that now make some of California's greatest reds.",
      "The name follows the French 'blanc de noirs' idea — a white (or pink) wine from black grapes.",
      "It was once the best-selling premium wine in the United States, introducing millions of Americans to wine."
    ]
  },
  {
    id: "rosato-rosado",
    name: "Rosato & Rosado",
    pronounce: "ro-zah-toh / ro-sah-doh",
    category: "rose",
    tagline: "The Mediterranean's deeper pinks",
    hue: ["#f2929d", "#dd5f77"],
    origin: "Italy & Spain (ancient traditions)",
    regions: ["Cerasuolo d'Abruzzo & Puglia, Italy", "Navarra & Rioja, Spain", "Tavel, France (the deep French cousin)"],
    abv: "12–14%",
    sweetness: 0, body: 3, tannin: 2, acidity: 4,
    servingTemp: "8–12 °C (46–54 °F)",
    glassware: "White wine or small red glass",
    flavors: ["Sour cherry", "Blood orange", "Pomegranate", "Watermelon", "Dried herbs", "White pepper"],
    pairings: ["Paella", "Grilled octopus", "Pizza", "Charcuterie", "Tomato-based dishes"],
    description: "Italy's rosato and Spain's rosado are rosé's bolder siblings — deeper coloured, more savoury and built for the table. Tavel in France goes further still: a rosé so dark and structured it's treated like a red.",
    facts: [
      "Cerasuolo d'Abruzzo takes its name from 'cerasa' — cherry — for its vivid cherry-red colour.",
      "Tavel is France's only appellation that produces rosé and nothing else; it was a favourite of Ernest Hemingway and King Philippe IV.",
      "Spanish rosado is traditionally made by 'sangrado' (bleeding) — drawing pink juice off a red-wine ferment.",
      "Puglia's rosato tradition began with 'lacrima' wines — 'tears' of juice run off with almost no pressing.",
      "Darker rosés aren't sweeter — colour comes from skin time, not sugar; most rosato/rosado is bone dry."
    ]
  },

  // ================= SPARKLING WINES =================
  {
    id: "champagne",
    name: "Champagne",
    pronounce: "sham-payn",
    category: "sparkling",
    tagline: "The original celebration",
    hue: ["#f5e3a0", "#e0be60"],
    origin: "Champagne, France (méthode perfected 17th–18th century)",
    regions: ["Reims, Épernay & the Champagne AOC only"],
    abv: "12–12.5%",
    sweetness: 1, body: 3, tannin: 0, acidity: 5,
    servingTemp: "8–10 °C (46–50 °F)",
    glassware: "Tulip glass (better than a flute!)",
    flavors: ["Green apple", "Citrus", "Brioche", "Toasted almond", "Cream", "Chalk"],
    pairings: ["Oysters", "Fried chicken (a sommelier favourite)", "Caviar", "Fish and chips", "Parmesan"],
    description: "The world's most famous sparkling wine, made only in Champagne, France, from Chardonnay, Pinot Noir and Pinot Meunier. Its bubbles come from a second fermentation inside each bottle, and its toasty magic from years resting on spent yeast cells in chalk cellars.",
    facts: [
      "Dom Pérignon didn't invent sparkling wine — the monk actually spent years trying to remove the bubbles, which shattered bottles. (The English were deliberately sparkling their wine earlier, in the 1660s.)",
      "The pressure inside a Champagne bottle is about 6 atmospheres — roughly triple a car tyre — which is why the cork can fly at 40+ km/h.",
      "A single glass releases around one million bubbles.",
      "Non-vintage Champagne must age at least 15 months on its lees; vintage must age 36 — top houses go far longer.",
      "During WWI, vineyards were battlefields; locals pressed harvests in cellars while shells fell, and Reims' chalk caves sheltered thousands of people.",
      "'Sabrage' — opening a bottle with a sabre — was popularised by Napoleon's cavalry officers celebrating victories."
    ]
  },
  {
    id: "prosecco",
    name: "Prosecco",
    pronounce: "pro-sek-oh",
    category: "sparkling",
    tagline: "Italy's frothy favourite",
    hue: ["#f3e8a5", "#dfc562"],
    origin: "Veneto & Friuli, Italy",
    regions: ["Valdobbiadene & Conegliano (the hills)", "Treviso", "Prosecco DOC (the wider zone)"],
    abv: "10.5–12%",
    sweetness: 2, body: 2, tannin: 0, acidity: 4,
    servingTemp: "6–8 °C (43–46 °F)",
    glassware: "Tulip or white wine glass",
    flavors: ["Green pear", "Honeydew melon", "White flowers", "Green apple", "Cream soda", "Honeysuckle"],
    pairings: ["Aperitivo snacks", "Prosciutto & melon", "Sushi", "Brunch dishes", "Aperol Spritz (as an ingredient)"],
    description: "The world's best-selling sparkling wine — light, fruity, flowery and affordable. Unlike Champagne, Prosecco gets its bubbles from a second fermentation in big steel tanks (the Martinotti/Charmat method), which keeps it fresh and pear-scented.",
    facts: [
      "Prosecco outsells Champagne globally — over 600 million bottles a year.",
      "The grape was renamed 'Glera' in 2009 so 'Prosecco' could be legally protected as a place name.",
      "The steep Valdobbiadene hills are a UNESCO World Heritage Site, farmed by hand on grassy terraces called 'ciglioni'.",
      "Tank-method production preserves primary fruit aromas — the reason Prosecco tastes of pear and Champagne of toast.",
      "'Cartizze', a single 107-hectare hill, is Prosecco's unofficial grand cru — land there is among Italy's most valuable farmland."
    ]
  },
  {
    id: "cava",
    name: "Cava",
    pronounce: "kah-vah",
    category: "sparkling",
    tagline: "Spain's cellar-born sparkler",
    hue: ["#f2e39c", "#dcc05e"],
    origin: "Penedès, Catalonia, Spain (1872)",
    regions: ["Sant Sadurní d'Anoia, Catalonia", "small zones across Spain"],
    abv: "11.5–12.5%",
    sweetness: 1, body: 3, tannin: 0, acidity: 4,
    servingTemp: "6–8 °C (43–46 °F)",
    glassware: "Tulip glass",
    flavors: ["Quince", "Lime", "Almond", "Bread dough", "Chamomile", "Pear"],
    pairings: ["Tapas", "Jamón", "Fried calamari", "Paella", "Potato crisps (truly)"],
    description: "Spain's traditional-method sparkler, made mostly from local grapes Macabeo, Xarel·lo and Parellada. Cava is produced exactly like Champagne — second fermentation in bottle — but sells for a fraction of the price.",
    facts: [
      "'Cava' simply means 'cellar' in Catalan — the wines age in vast underground labyrinths.",
      "Josep Raventós of Codorníu made the first bottle in 1872 after visiting Champagne.",
      "One producer, Freixenet, ships more traditional-method sparkling wine than any Champagne house.",
      "Cava de Paraje Calificado, created in 2017, is a single-estate top tier requiring 36 months of ageing.",
      "The local grape Xarel·lo is one of the world's most antioxidant-rich white grapes, helping Cava age surprisingly well."
    ]
  },
  {
    id: "cremant",
    name: "Crémant",
    pronounce: "kray-mahn",
    category: "sparkling",
    tagline: "France's insider secret",
    hue: ["#f4e6a2", "#e2c467"],
    origin: "France (eight regional appellations)",
    regions: ["Crémant d'Alsace", "Crémant de Loire", "Crémant de Bourgogne", "Crémant de Limoux", "plus four more"],
    abv: "11.5–12.5%",
    sweetness: 1, body: 3, tannin: 0, acidity: 4,
    servingTemp: "7–9 °C (45–48 °F)",
    glassware: "Tulip glass",
    flavors: ["Baked apple", "Citrus", "Brioche", "White flowers", "Stone fruit", "Hazelnut"],
    pairings: ["Canapés", "Soft cheeses", "Roast poultry", "Seafood", "Quiche Lorraine"],
    description: "Champagne-method sparkling wine from everywhere in France except Champagne. Each region uses its own grapes — Chenin in the Loire, Pinot Blanc in Alsace, Chardonnay in Burgundy — making Crémant the savvy drinker's best-value bubble.",
    facts: [
      "'Crémant' originally described a gently 'creaming' (half-pressure) fizz; it became the official name for non-Champagne traditional-method wines in 1975.",
      "By law Crémant grapes must be hand-harvested and whole-bunch pressed — the same rule as Champagne.",
      "Limoux claims sparkling wine was invented there by Benedictine monks in 1531 — over a century before Champagne fizzed.",
      "All Crémants must age at least 9 months on lees; many exceed Champagne's minimum.",
      "There are eight Crémant appellations: Alsace, Bordeaux, Bourgogne, Die, Jura, Limoux, Loire and Savoie."
    ]
  },
  {
    id: "franciacorta",
    name: "Franciacorta",
    pronounce: "fran-cha-kor-tah",
    category: "sparkling",
    tagline: "Italy's answer to Champagne",
    hue: ["#f3e29e", "#ddbe5f"],
    origin: "Lombardy, Italy (modern era from 1961)",
    regions: ["Franciacorta, near Lake Iseo, Lombardy"],
    abv: "12–13%",
    sweetness: 1, body: 3, tannin: 0, acidity: 4,
    servingTemp: "8–10 °C (46–50 °F)",
    glassware: "Tulip glass",
    flavors: ["Ripe citrus", "Brioche", "Almond pastry", "White peach", "Hazelnut", "Cream"],
    pairings: ["Risotto alla milanese", "Raw fish crudo", "Aged Parmigiano", "Roast veal", "Truffle dishes"],
    description: "Italy's most prestigious sparkling wine — traditional bottle fermentation like Champagne, but with riper Lombardy fruit giving a rounder, sunnier style. Little known abroad because Italians drink nearly all of it themselves.",
    facts: [
      "The modern industry began in 1961 when young winemaker Franco Ziliani convinced the Berlucchi estate to try a 'Champagne-style' wine — 3,000 bottles that launched a region.",
      "Franciacorta must age longer than Champagne: at least 18 months on lees (Champagne NV: 15), and 60 for riservas.",
      "The name may come from 'curtes francae' — medieval monastic courts exempt from taxes.",
      "Its 'Satèn' style is uniquely Italian: Chardonnay-based, bottled at lower pressure for a silky, satin mousse.",
      "Only around 10% is exported — the rest never leaves Italy."
    ]
  },
  {
    id: "lambrusco",
    name: "Lambrusco",
    pronounce: "lam-broos-koh",
    category: "sparkling",
    tagline: "The fizzy red rebel",
    hue: ["#a02545", "#5c0f26"],
    origin: "Emilia-Romagna, Italy (praised by Virgil, 1st c. BC)",
    regions: ["Modena, Reggio Emilia & Parma provinces"],
    abv: "10.5–12%",
    sweetness: 2, body: 3, tannin: 2, acidity: 4,
    servingTemp: "10–12 °C (50–54 °F)",
    glassware: "Tulip or standard glass",
    flavors: ["Black cherry", "Blackberry", "Violet", "Rhubarb", "Fresh cream", "Watermelon (rosé styles)"],
    pairings: ["Parma ham & salumi", "Lasagne", "Parmigiano-Reggiano", "Pizza", "Tortelli"],
    description: "Yes — sparkling red wine. Lambrusco is the frothy purple companion to Emilia-Romagna's rich food (this is the land of Parmesan, balsamic and prosciutto). Dismissed abroad after a 1970s sweet-fizz boom, real dry ('secco') Lambrusco is one of Italy's great food wines.",
    facts: [
      "The Roman poet Virgil — born near Mantua — wrote about the wild 'labrusca' vine 2,000 years ago.",
      "In the 1970s–80s sweet Lambrusco was the best-selling imported wine in the USA, nicknamed 'Italian Coca-Cola'.",
      "There are over a dozen distinct Lambrusco grape varieties — Sorbara makes the palest and most elegant, Grasparossa the darkest and grippiest.",
      "The froth ('spuma') is traditionally seen as a scrubber for Emilia's famously rich, fatty cuisine.",
      "Traditional bottles were sealed with a crown cap — like a beer bottle — and many still are."
    ]
  },
  {
    id: "sparkling-rose",
    name: "Sparkling Rosé",
    pronounce: "spar-kling ro-zay",
    category: "sparkling",
    tagline: "Pink bubbles, serious craft",
    hue: ["#f4b8bd", "#e7889a"],
    origin: "Champagne, France (Ruinart, 1764)",
    regions: ["Champagne", "Crémant regions", "England", "California", "Australia & NZ"],
    abv: "11.5–12.5%",
    sweetness: 1, body: 3, tannin: 0, acidity: 5,
    servingTemp: "7–9 °C (45–48 °F)",
    glassware: "Tulip glass",
    flavors: ["Wild strawberry", "Redcurrant", "Blood orange", "Rose petal", "Brioche", "Cream"],
    pairings: ["Salmon", "Duck", "Berry desserts", "Festive dinners", "Soft cheeses"],
    description: "From pale-salmon Champagne rosé to vivid pink Australian sparklers, pink fizz combines red-berry fruit with the refreshment of bubbles. In Champagne, uniquely, producers may simply blend a little still red wine into the white base.",
    facts: [
      "Champagne is the only French appellation allowed to make rosé by blending red and white wine — everywhere else it's forbidden.",
      "Ruinart shipped the first recorded rosé Champagne in 1764, listed as 'Oeil de Perdrix' — 'partridge eye' pink.",
      "Rosé Champagne usually costs more than white: red Pinot Noir for blending is scarce and hard to make.",
      "The alternative method, 'saignée', bleeds colour from black grape skins for a deeper, fruitier style.",
      "Queen Elizabeth II was said to favour pink Champagne — as did Winston Churchill's mother, who helped make it fashionable in society."
    ]
  },

  // ================= DESSERT WINES =================
  {
    id: "sauternes",
    name: "Sauternes",
    pronounce: "soh-tairn",
    category: "dessert",
    tagline: "Noble rot's golden gift",
    hue: ["#eec158", "#c98f2b"],
    origin: "Sauternes, Bordeaux, France",
    regions: ["Sauternes & Barsac, Bordeaux"],
    abv: "13–14%",
    sweetness: 5, body: 5, tannin: 0, acidity: 4,
    servingTemp: "6–8 °C (43–46 °F)",
    glassware: "Small dessert wine glass",
    flavors: ["Apricot jam", "Honey", "Saffron", "Candied orange", "Marmalade", "Botrytis 'ginger' spice"],
    pairings: ["Roquefort (the classic)", "Foie gras", "Crème brûlée", "Peach desserts", "Salted caramel"],
    description: "The world's most celebrated sweet wine, made from grapes attacked by 'noble rot' — a fungus that shrivels the berries and concentrates their sugar into liquid gold. Morning mists off the little river Ciron make the magic happen.",
    facts: [
      "Noble rot is the fungus Botrytis cinerea: in humid mornings and dry afternoons it dehydrates grapes perfectly instead of ruining them.",
      "Pickers pass through the vineyard up to 6 times ('tries'), selecting single shrivelled berries by hand.",
      "One vine at Château d'Yquem yields roughly one glass of wine — versus a bottle or more elsewhere.",
      "A bottle of 1811 'Comet Vintage' Yquem sold for £75,000, and the wine can age over 200 years.",
      "Thomas Jefferson adored Yquem and ordered hundreds of bottles for himself and George Washington in 1787."
    ]
  },
  {
    id: "ice-wine",
    name: "Ice Wine / Eiswein",
    pronounce: "ice-wine / ice-vine",
    category: "dessert",
    tagline: "Harvested frozen at midnight",
    hue: ["#f2d979", "#dfae3f"],
    origin: "Franconia, Germany (1794, by accident)",
    regions: ["Niagara Peninsula, Canada", "Germany & Austria", "Okanagan, Canada", "China (emerging)"],
    abv: "9–12%",
    sweetness: 5, body: 4, tannin: 0, acidity: 5,
    servingTemp: "6–8 °C (43–46 °F)",
    glassware: "Small tulip dessert glass",
    flavors: ["Lychee", "Frozen peach", "Mango", "Honey", "Candied lime", "Tropical nectar"],
    pairings: ["Fruit tarts", "Cheesecake", "Blue cheese", "Foie gras", "Simply on its own"],
    description: "Made from healthy grapes left to freeze solid on the vine, then picked and pressed — often at night — while still frozen at −8 °C or below. The water stays behind as ice crystals; only drops of intensely sweet nectar are squeezed out.",
    facts: [
      "Legend dates Eiswein to 1794 in Franconia, when growers pressed accidentally frozen grapes rather than waste them.",
      "Canada's Niagara Peninsula is now the world's largest producer — its winters freeze reliably every year, unlike Germany's.",
      "Harvest happens at night or before dawn, by hand, in temperatures around −10 °C.",
      "Yields are minuscule: a whole vine may give just enough juice for half a small bottle.",
      "Genuine ice wine may never use artificially frozen grapes — cryoextraction wines must be labelled differently.",
      "Vidal and Riesling are the classic grapes; Cabernet Franc ice wine is a striking pink Canadian speciality."
    ]
  },
  {
    id: "tokaji",
    name: "Tokaji Aszú",
    pronounce: "tok-eye ah-soo",
    category: "dessert",
    tagline: "Wine of kings, king of wines",
    hue: ["#e8b445", "#b97e1e"],
    origin: "Tokaj, Hungary (aszú documented 1571)",
    regions: ["Tokaj region, Hungary & Slovakia"],
    abv: "9–13%",
    sweetness: 5, body: 4, tannin: 0, acidity: 5,
    servingTemp: "8–10 °C (46–50 °F)",
    glassware: "Small tulip dessert glass",
    flavors: ["Dried apricot", "Orange marmalade", "Honey", "Barley sugar", "Saffron", "Green tea"],
    pairings: ["Foie gras", "Blue cheese", "Peach melba", "Apricot pastries", "Rich pâtés"],
    description: "Hungary's amber treasure, made from hand-picked botrytised 'aszú' berries mashed into a base wine. Louis XIV himself declared Tokaji 'the wine of kings, the king of wines' — 200 years before Bordeaux's famous classification, Tokaj had already classified its vineyards.",
    facts: [
      "Tokaj's vineyards were classified into growths in 1737 — the world's first national vineyard classification, pre-dating Bordeaux's 1855 ranking by over a century.",
      "Sweetness was traditionally measured in 'puttonyos' — the number of hods of aszú berries added per barrel.",
      "Russian tsars kept a permanent garrison in Tokaj to escort their wine shipments to St Petersburg.",
      "The rare 'Eszencia' — free-run juice of pure aszú berries — can take decades to ferment to just a few percent alcohol and was reserved for royalty and the dying.",
      "Tokaji is name-checked in Hungary's national anthem, and the region is a UNESCO World Heritage Site."
    ]
  },
  {
    id: "late-harvest",
    name: "Late Harvest Wines",
    pronounce: "layt har-vist",
    category: "dessert",
    tagline: "Patience rewarded in sugar",
    hue: ["#efce6d", "#d5a338"],
    origin: "Germany (Spätlese, 1775) & worldwide",
    regions: ["Germany (Spätlese/Auslese)", "Alsace (Vendange Tardive)", "Chile & California", "South Africa"],
    abv: "8–14%",
    sweetness: 4, body: 3, tannin: 0, acidity: 4,
    servingTemp: "7–9 °C (45–48 °F)",
    glassware: "Small white or dessert glass",
    flavors: ["Ripe apricot", "Honey", "Baked pineapple", "Raisin", "Candied citrus", "Flowers"],
    pairings: ["Fruit desserts", "Soft blue cheeses", "Spicy food (lighter styles)", "Pâté", "Almond cakes"],
    description: "The simplest route to sweet wine: leave grapes hanging weeks past normal harvest until they're loaded with sugar — sometimes raisining on the vine. Every wine country has its version, from German Spätlese to Alsace's Vendange Tardive.",
    facts: [
      "The style was born by accident at Schloss Johannisberg in 1775, when the messenger authorising harvest arrived too late — 'Spätlese' literally means 'late picking'.",
      "Riper still are Auslese (selected bunches), and beyond that Beerenauslese and Trockenbeerenauslese — individual shrivelled berries.",
      "Hanging grapes late is a gamble: rain, birds, rot or frost can destroy the whole crop in a day.",
      "Late-harvest wines can be made from almost any grape — Riesling, Gewürztraminer, Chenin, Sémillon and Zinfandel all shine.",
      "Because sugar keeps rising while acid falls, the world's best late-harvest wines come from cool regions where acidity survives the wait."
    ]
  },
  {
    id: "vin-santo",
    name: "Vin Santo",
    pronounce: "vin sahn-toh",
    category: "dessert",
    tagline: "Tuscany's holy wine",
    hue: ["#d99a35", "#a06618"],
    origin: "Tuscany, Italy (medieval)",
    regions: ["Chianti & Montepulciano, Tuscany", "Trentino (Vino Santo)", "Umbria"],
    abv: "14–17%",
    sweetness: 4, body: 4, tannin: 0, acidity: 4,
    servingTemp: "10–12 °C (50–54 °F)",
    glassware: "Small tulip or sherry glass",
    flavors: ["Hazelnut", "Caramel", "Dried fig", "Raisin", "Honey", "Old furniture polish (in the best way)"],
    pairings: ["Cantucci biscuits (the ritual)", "Almond desserts", "Aged pecorino", "Panforte", "Espresso-adjacent moments"],
    description: "Tuscany's 'holy wine': grapes dried for months on straw mats in airy lofts, then fermented and sealed into small barrels ('caratelli') for years under the roof, through summer heat and winter cold. The result is amber, nutty and contemplative — served with almond biscotti for dunking.",
    facts: [
      "The barrels are left in attics on purpose — the temperature swings drive slow oxidation that creates the flavour.",
      "Each barrel keeps its 'madre' (mother) — a residue of previous vintages that kick-starts fermentation, like a sourdough starter.",
      "One legend credits the name to a friar whose 'holy' altar wine healed plague victims in 1348; another to a Greek cardinal exclaiming the wine was like Xantho.",
      "Fermentation in the sealed caratelli can take up to four years — one of the slowest of any wine.",
      "Dunking cantucci in Vin Santo is Tuscany's national dessert — though purists insist the best bottles deserve to be sipped alone."
    ]
  },
  {
    id: "moscato-dasti",
    name: "Moscato d'Asti",
    pronounce: "mos-kah-toh das-tee",
    category: "dessert",
    tagline: "A whisper of sweet fizz",
    hue: ["#f6e9a0", "#e5c65f"],
    origin: "Asti, Piedmont, Italy",
    regions: ["Asti, Alba & the Langhe hills, Piedmont"],
    abv: "5–5.5%",
    sweetness: 4, body: 1, tannin: 0, acidity: 4,
    servingTemp: "6–8 °C (43–46 °F)",
    glassware: "Small tulip or white wine glass",
    flavors: ["Peach", "Orange blossom", "Grape", "Honeysuckle", "Ginger", "Mandarin"],
    pairings: ["Panettone", "Fruit salad", "Hazelnut cake", "Brunch", "Birthday cake"],
    description: "Piedmont's gently sparkling, gently sweet, barely alcoholic charmer — just 5.5% ABV. Made from Muscat Blanc à Petits Grains, its fermentation is chilled to a stop while the wine is still sweet and softly 'frizzante'.",
    facts: [
      "At around 5.5% alcohol, Moscato d'Asti is one of the lightest wines made anywhere.",
      "Piedmontese winemakers traditionally drink it at the END of a long lunch — a palate refresher after Barolo.",
      "It's 'frizzante' (semi-sparkling, under 2.5 atmospheres), so it comes with a normal cork, not a Champagne cage.",
      "The wine's whole character depends on stopping fermentation by chilling and filtering — a technique perfected in the 1960s with refrigeration.",
      "Its big brother Asti Spumante is fully sparkling and slightly stronger; Moscato d'Asti is the artisan, small-production sibling."
    ]
  },

  // ================= FORTIFIED WINES =================
  {
    id: "port",
    name: "Port",
    pronounce: "port",
    category: "fortified",
    tagline: "The Douro's dark treasure",
    hue: ["#5c1029", "#2b0715"],
    origin: "Douro Valley, Portugal (trade est. 17th century)",
    regions: ["Douro Valley (vineyards)", "Vila Nova de Gaia (lodges)", "styles: Ruby, Tawny, Vintage, LBV, White, Rosé"],
    abv: "19–22%",
    sweetness: 4, body: 5, tannin: 4, acidity: 3,
    servingTemp: "12–16 °C (54–61 °F); white/tawny cooler",
    glassware: "Small port glass",
    flavors: ["Blackberry compote", "Raisin", "Dark chocolate", "Cinnamon", "Walnut & caramel (tawny)", "Fig"],
    pairings: ["Stilton (the immortal pairing)", "Dark chocolate desserts", "Walnuts", "Pecan pie", "A fireplace"],
    description: "Portugal's great fortified red, born when brandy was added to Douro wine to survive shipment to England. Fortification stops fermentation early, keeping natural grape sweetness at 19–22% alcohol. Vintage Port can age a century; nutty Tawny ages for decades in barrel instead.",
    facts: [
      "The Douro was demarcated and regulated in 1756 — one of the world's first legally protected wine regions.",
      "Vintage Port is 'declared' only in exceptional years — typically about three per decade — and bottled unfiltered after two years.",
      "Grapes are still foot-trodden in granite 'lagares' at top houses; feet crush skins without cracking bitter seeds.",
      "Over 80 grape varieties are permitted; Touriga Nacional is the star.",
      "The English connection runs deep: many great houses (Taylor's, Graham's, Dow's) bear British names from the 1700s trade.",
      "Traditionally the decanter passes 'to the left' around a British dinner table — stalling it is a social crime worth a gentle scolding."
    ]
  },
  {
    id: "sherry",
    name: "Sherry",
    pronounce: "sheh-ree",
    category: "fortified",
    tagline: "Andalusia's flor-kissed marvel",
    hue: ["#e3b654", "#9c6b1f"],
    origin: "Jerez de la Frontera, Spain (3,000 years of wine)",
    regions: ["The 'Sherry Triangle': Jerez, Sanlúcar de Barrameda & El Puerto de Santa María", "styles: Fino, Manzanilla, Amontillado, Oloroso, Palo Cortado, PX"],
    abv: "15–22%",
    sweetness: 1, body: 3, tannin: 0, acidity: 4,
    servingTemp: "7–9 °C fino; 12–14 °C oloroso",
    glassware: "Copita (small tulip)",
    flavors: ["Green apple & almond (fino)", "Sea air", "Hazelnut (amontillado)", "Walnut & leather (oloroso)", "Coffee & fig (PX)", "Bread dough (flor)"],
    pairings: ["Jamón & olives (fino)", "Almonds", "Consommé", "Mushrooms (amontillado)", "Vanilla ice cream drowned in PX"],
    description: "The most diverse wine style on Earth: bone-dry saline Fino aged under a living veil of yeast ('flor'), nutty oxidative Oloroso, and treacle-black Pedro Ximénez — all blended through cascading barrel systems ('soleras') where some wine components are over a century old.",
    facts: [
      "Flor — a film of living yeast — grows on Fino's surface in the barrel, protecting it from air and adding a signature tang. It's unique to the region's climate.",
      "The solera system blends dozens of vintages: wine is drawn from the oldest barrels and refilled from younger ones, so a solera started in 1847 still flavours today's bottling.",
      "Magellan spent more on sherry than on weapons when provisioning his 1519 circumnavigation.",
      "Shakespeare's Falstaff rhapsodises about 'sherris-sack'; Elizabethan England was sherry-mad after Francis Drake 'liberated' 2,900 barrels from Cádiz in 1587.",
      "Pedro Ximénez (PX) is made from sun-dried grapes and can exceed 400 g/L of sugar — one of the sweetest liquids in the wine world, yet Fino from the same region is one of the driest wines made.",
      "A Fino must age at least two years under flor; the yeast eats glycerine, which is why Fino is so razor-dry and light on its feet."
    ]
  },
  {
    id: "madeira",
    name: "Madeira",
    pronounce: "muh-dair-ah",
    category: "fortified",
    tagline: "The immortal island wine",
    hue: ["#b5731f", "#7a4a10"],
    origin: "Madeira island, Portugal (15th century)",
    regions: ["Madeira, Atlantic Ocean", "styles: Sercial (dry) → Verdelho → Bual → Malmsey (sweet)"],
    abv: "17–20%",
    sweetness: 3, body: 4, tannin: 1, acidity: 5,
    servingTemp: "13–16 °C (55–61 °F)",
    glassware: "Small tulip glass",
    flavors: ["Toffee", "Roasted nuts", "Burnt orange", "Green peppercorn", "Dried fruit", "Volcanic smoke"],
    pairings: ["Aperitif olives (Sercial)", "Mushroom soup", "Sticky toffee pudding (Malmsey)", "Roquefort", "Chocolate"],
    description: "The wine that cannot die. Madeira is deliberately heated and oxidised — a process discovered when barrels crossing the tropics as ship's ballast came back tasting better. Once made, it is essentially indestructible: bottles from the 1700s are still drinkable, even delicious.",
    facts: [
      "An open bottle of Madeira stays fresh for months or years — it has already been 'cooked' and oxidised on purpose.",
      "The style was discovered when unsold barrels ('vinho da roda') returned from round trips across the equator transformed for the better.",
      "Modern producers replicate the voyage in 'estufas' (heated tanks) or 'canteiro' attics warmed by the sun for decades.",
      "Madeira was used to toast the American Declaration of Independence in 1776 — the Founding Fathers were devoted fans.",
      "The island's vineyards grow on volcanic terraces ('poios') laced with historic levada irrigation channels.",
      "Bottles over 200 years old are regularly opened and found alive — critics have rated 18th-century Madeiras among the greatest wines they've ever tasted."
    ]
  },
  {
    id: "marsala",
    name: "Marsala",
    pronounce: "mar-sah-lah",
    category: "fortified",
    tagline: "Sicily's kitchen legend",
    hue: ["#a35d1c", "#6b390e"],
    origin: "Marsala, Sicily (1773, John Woodhouse)",
    regions: ["Western Sicily (Trapani province)", "styles: Fine, Superiore, Vergine/Soleras; Oro, Ambra, Rubino"],
    abv: "17–20%",
    sweetness: 3, body: 4, tannin: 1, acidity: 3,
    servingTemp: "10–14 °C (50–57 °F)",
    glassware: "Small tulip or sherry glass",
    flavors: ["Dried apricot", "Vanilla", "Brown sugar", "Tamarind", "Hazelnut", "Tobacco"],
    pairings: ["Zabaglione (made with it)", "Aged cheeses", "Almond biscotti", "Dried figs", "Chicken or veal Marsala (in the pan)"],
    description: "Sicily's historic fortified wine, launched in 1773 when English trader John Woodhouse fortified local wine to survive the voyage home. Known worldwide as a cooking wine, real aged Marsala — especially dry 'Vergine' — is a serious sipping wine to rival dry sherry.",
    facts: [
      "John Woodhouse shipped the first fortified Marsala to Liverpool in 1773 after taking shelter in the port during a storm.",
      "Admiral Nelson ordered vast supplies for the Royal Navy in 1798, calling it worthy of 'any gentleman's table' — victory at Trafalgar made it patriotic to drink.",
      "Garibaldi landed at Marsala in 1860 to begin the unification of Italy; a sweet style is still named 'Garibaldi Dolce'.",
      "Marsala Vergine must be bone dry and aged at least five years (ten for Soleras Riserva).",
      "It comes in three colours — Oro (gold), Ambra (amber) and Rubino (ruby) — and its DOC, created in 1969, was among Italy's first."
    ]
  },
  {
    id: "vermouth",
    name: "Vermouth",
    pronounce: "ver-mooth",
    category: "fortified",
    tagline: "Wine dressed in botanicals",
    hue: ["#c98f3d", "#8a5a1c"],
    origin: "Turin, Italy (Antonio Benedetto Carpano, 1786)",
    regions: ["Turin, Italy (rosso/sweet)", "Chambéry & Marseille, France (dry)", "Reus, Spain"],
    abv: "15–18%",
    sweetness: 3, body: 3, tannin: 1, acidity: 3,
    servingTemp: "6–10 °C (43–50 °F), over ice is fine",
    glassware: "Rocks glass or small tulip",
    flavors: ["Wormwood bitterness", "Vanilla", "Orange peel", "Clove & cinnamon", "Alpine herbs", "Caramel (rosso)"],
    pairings: ["Olives & crisps (Spanish 'la hora del vermut')", "Anchovies", "Hard cheeses", "Negronis & Martinis (as an ingredient)", "Citrusy desserts"],
    description: "An aromatised, fortified wine infused with botanicals — always including wormwood, from whose German name ('Wermut') it takes its own. Born in Turin's cafés, it became the backbone of the world's greatest cocktails and, in Spain, a beloved drink in its own right with its own hour of the day.",
    facts: [
      "Vermouth by law must be at least 75% wine, and must contain wormwood (Artemisia).",
      "Antonio Benedetto Carpano created modern sweet vermouth in Turin in 1786; his shop stayed open 24 hours to meet demand.",
      "Hippocrates infused wine with wormwood as medicine 2,400 years ago — vermouth's true ancient ancestor.",
      "Spain's 'la hora del vermut' (the vermouth hour) is the pre-lunch ritual of vermouth on tap with olives and crisps.",
      "The Martini and the Negroni are both, technically, vermouth cocktails — it's the defining ingredient of both.",
      "Being wine-based, vermouth oxidises: an open bottle belongs in the fridge and should be finished within a month or two."
    ]
  },

  // ================= ORANGE / SKIN-CONTACT =================
  {
    id: "orange-wine",
    name: "Orange Wine (Skin-Contact)",
    pronounce: "or-anj wine",
    category: "orange",
    tagline: "8,000 years of amber",
    hue: ["#e09b3f", "#a5651c"],
    origin: "Georgia (Caucasus), ~6,000 BC",
    regions: ["Kakheti, Georgia (qvevri wines)", "Friuli & Slovenia (Brda/Collio)", "worldwide natural-wine scene"],
    abv: "11–14%",
    sweetness: 0, body: 4, tannin: 3, acidity: 4,
    servingTemp: "10–14 °C (50–57 °F)",
    glassware: "Standard white or Burgundy glass",
    flavors: ["Dried apricot", "Bruised apple", "Black tea", "Honey", "Hazelnut", "Sourdough & orchard funk"],
    pairings: ["Curry & spiced food", "Aged hard cheeses", "Fermented dishes (kimchi!)", "Roast poultry", "Georgian khachapuri"],
    description: "White grapes made like red wine: fermented for days, weeks or months on their skins, gaining amber colour, gentle tannin and wild aromas of tea, dried fruit and nuts. It's the newest trend in wine — and also, by far, the oldest way of making it.",
    facts: [
      "Georgia has made wine in buried clay vessels ('qvevri') for about 8,000 years — the world's oldest continuous winemaking tradition, recognised by UNESCO.",
      "Archaeologists found wine residue on 6,000 BC pottery shards near Tbilisi — the earliest evidence of winemaking anywhere.",
      "The term 'orange wine' was coined in 2004 by a British wine importer, David A. Harvey.",
      "Qvevri are beeswax-lined clay eggs buried to the neck in the earth, which keeps fermentation naturally cool.",
      "The modern revival started in the 1990s when Friulian winemakers Joško Gravner and Stanko Radikon returned to ancient skin-contact methods — Gravner even imported qvevri from Georgia.",
      "Despite the colour, there are no oranges involved — ever. It's purely grape skins."
    ]
  }
];
